"""remove_admin_auth

Revision ID: 28f66ff50d0f
Revises: 7753db94e2ae
Create Date: 2026-05-29 12:07:06.927297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28f66ff50d0f'
down_revision: Union[str, Sequence[str], None] = '7753db94e2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop FK constraint and column first, then the table
    op.drop_constraint(op.f('polls_admin_id_fkey'), 'polls', type_='foreignkey')
    op.drop_column('polls', 'admin_id')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('polls_admin_id_fkey'), 'polls', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    # ### end Alembic commands ###
